package com.optimussoftware.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ADVERTISING_INTEREST".
*/
public class AdvertisingInterestDao extends AbstractDao<AdvertisingInterest, Long> {

    public static final String TABLENAME = "ADVERTISING_INTEREST";

    /**
     * Properties of entity AdvertisingInterest.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Advertising_id = new Property(1, String.class, "advertising_id", false, "ADVERTISING_ID");
        public final static Property Interest_id = new Property(2, String.class, "interest_id", false, "INTEREST_ID");
    }


    public AdvertisingInterestDao(DaoConfig config) {
        super(config);
    }
    
    public AdvertisingInterestDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ADVERTISING_INTEREST\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"ADVERTISING_ID\" TEXT," + // 1: advertising_id
                "\"INTEREST_ID\" TEXT);"); // 2: interest_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ADVERTISING_INTEREST\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AdvertisingInterest entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String advertising_id = entity.getAdvertising_id();
        if (advertising_id != null) {
            stmt.bindString(2, advertising_id);
        }
 
        String interest_id = entity.getInterest_id();
        if (interest_id != null) {
            stmt.bindString(3, interest_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AdvertisingInterest entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String advertising_id = entity.getAdvertising_id();
        if (advertising_id != null) {
            stmt.bindString(2, advertising_id);
        }
 
        String interest_id = entity.getInterest_id();
        if (interest_id != null) {
            stmt.bindString(3, interest_id);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AdvertisingInterest readEntity(Cursor cursor, int offset) {
        AdvertisingInterest entity = new AdvertisingInterest( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // advertising_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // interest_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AdvertisingInterest entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAdvertising_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setInterest_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AdvertisingInterest entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AdvertisingInterest entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AdvertisingInterest entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
