package com.optimussoftware.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ADVERTISING_IMAGE".
 */
@Entity
public class AdvertisingImage {

    @Id(autoincrement = true)
    @Unique
    private Long id;
    private String advertising_id;
    private String image_id;

    @Generated
    public AdvertisingImage() {
    }

    public AdvertisingImage(Long id) {
        this.id = id;
    }

    @Generated
    public AdvertisingImage(Long id, String advertising_id, String image_id) {
        this.id = id;
        this.advertising_id = advertising_id;
        this.image_id = image_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAdvertising_id() {
        return advertising_id;
    }

    public void setAdvertising_id(String advertising_id) {
        this.advertising_id = advertising_id;
    }

    public String getImage_id() {
        return image_id;
    }

    public void setImage_id(String image_id) {
        this.image_id = image_id;
    }

}
