package com.optimussoftware.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ADVERTISING_INTEREST".
 */
@Entity
public class AdvertisingInterest {

    @Id(autoincrement = true)
    @Unique
    private Long id;
    private String advertising_id;
    private String interest_id;

    @Generated
    public AdvertisingInterest() {
    }

    public AdvertisingInterest(Long id) {
        this.id = id;
    }

    @Generated
    public AdvertisingInterest(Long id, String advertising_id, String interest_id) {
        this.id = id;
        this.advertising_id = advertising_id;
        this.interest_id = interest_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAdvertising_id() {
        return advertising_id;
    }

    public void setAdvertising_id(String advertising_id) {
        this.advertising_id = advertising_id;
    }

    public String getInterest_id() {
        return interest_id;
    }

    public void setInterest_id(String interest_id) {
        this.interest_id = interest_id;
    }

}
