package com.optimussoftware.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FAVORITES".
*/
public class FavoritesDao extends AbstractDao<Favorites, String> {

    public static final String TABLENAME = "FAVORITES";

    /**
     * Properties of entity Favorites.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, String.class, "_id", true, "_ID");
        public final static Property _etag = new Property(1, String.class, "_etag", false, "_ETAG");
        public final static Property Created = new Property(2, java.util.Date.class, "created", false, "CREATED");
        public final static Property Updated = new Property(3, java.util.Date.class, "updated", false, "UPDATED");
        public final static Property Active = new Property(4, Boolean.class, "active", false, "ACTIVE");
        public final static Property Deleted = new Property(5, Boolean.class, "deleted", false, "DELETED");
        public final static Property Advertising_id = new Property(6, String.class, "advertising_id", false, "ADVERTISING_ID");
        public final static Property User_id = new Property(7, String.class, "user_id", false, "USER_ID");
        public final static Property Location_id = new Property(8, String.class, "location_id", false, "LOCATION_ID");
    }

    private DaoSession daoSession;

    private Query<Favorites> user_TheUserFavoriteQuery;
    private Query<Favorites> location_TheLocationFavoriteQuery;

    public FavoritesDao(DaoConfig config) {
        super(config);
    }
    
    public FavoritesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FAVORITES\" (" + //
                "\"_ID\" TEXT PRIMARY KEY NOT NULL UNIQUE ," + // 0: _id
                "\"_ETAG\" TEXT," + // 1: _etag
                "\"CREATED\" INTEGER," + // 2: created
                "\"UPDATED\" INTEGER," + // 3: updated
                "\"ACTIVE\" INTEGER," + // 4: active
                "\"DELETED\" INTEGER," + // 5: deleted
                "\"ADVERTISING_ID\" TEXT," + // 6: advertising_id
                "\"USER_ID\" TEXT NOT NULL ," + // 7: user_id
                "\"LOCATION_ID\" TEXT);"); // 8: location_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FAVORITES\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Favorites entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.get_id());
 
        String _etag = entity.get_etag();
        if (_etag != null) {
            stmt.bindString(2, _etag);
        }
 
        java.util.Date created = entity.getCreated();
        if (created != null) {
            stmt.bindLong(3, created.getTime());
        }
 
        java.util.Date updated = entity.getUpdated();
        if (updated != null) {
            stmt.bindLong(4, updated.getTime());
        }
 
        Boolean active = entity.getActive();
        if (active != null) {
            stmt.bindLong(5, active ? 1L: 0L);
        }
 
        Boolean deleted = entity.getDeleted();
        if (deleted != null) {
            stmt.bindLong(6, deleted ? 1L: 0L);
        }
 
        String advertising_id = entity.getAdvertising_id();
        if (advertising_id != null) {
            stmt.bindString(7, advertising_id);
        }
        stmt.bindString(8, entity.getUser_id());
 
        String location_id = entity.getLocation_id();
        if (location_id != null) {
            stmt.bindString(9, location_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Favorites entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.get_id());
 
        String _etag = entity.get_etag();
        if (_etag != null) {
            stmt.bindString(2, _etag);
        }
 
        java.util.Date created = entity.getCreated();
        if (created != null) {
            stmt.bindLong(3, created.getTime());
        }
 
        java.util.Date updated = entity.getUpdated();
        if (updated != null) {
            stmt.bindLong(4, updated.getTime());
        }
 
        Boolean active = entity.getActive();
        if (active != null) {
            stmt.bindLong(5, active ? 1L: 0L);
        }
 
        Boolean deleted = entity.getDeleted();
        if (deleted != null) {
            stmt.bindLong(6, deleted ? 1L: 0L);
        }
 
        String advertising_id = entity.getAdvertising_id();
        if (advertising_id != null) {
            stmt.bindString(7, advertising_id);
        }
        stmt.bindString(8, entity.getUser_id());
 
        String location_id = entity.getLocation_id();
        if (location_id != null) {
            stmt.bindString(9, location_id);
        }
    }

    @Override
    protected final void attachEntity(Favorites entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    @Override
    public Favorites readEntity(Cursor cursor, int offset) {
        Favorites entity = new Favorites( //
            cursor.getString(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // _etag
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // created
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // updated
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // active
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // deleted
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // advertising_id
            cursor.getString(offset + 7), // user_id
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // location_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Favorites entity, int offset) {
        entity.set_id(cursor.getString(offset + 0));
        entity.set_etag(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCreated(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setUpdated(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setActive(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setDeleted(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setAdvertising_id(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUser_id(cursor.getString(offset + 7));
        entity.setLocation_id(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Favorites entity, long rowId) {
        return entity.get_id();
    }
    
    @Override
    public String getKey(Favorites entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Favorites entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "TheUserFavorite" to-many relationship of User. */
    public List<Favorites> _queryUser_TheUserFavorite(String user_id) {
        synchronized (this) {
            if (user_TheUserFavoriteQuery == null) {
                QueryBuilder<Favorites> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.User_id.eq(null));
                user_TheUserFavoriteQuery = queryBuilder.build();
            }
        }
        Query<Favorites> query = user_TheUserFavoriteQuery.forCurrentThread();
        query.setParameter(0, user_id);
        return query.list();
    }

    /** Internal query to resolve the "TheLocationFavorite" to-many relationship of Location. */
    public List<Favorites> _queryLocation_TheLocationFavorite(String location_id) {
        synchronized (this) {
            if (location_TheLocationFavoriteQuery == null) {
                QueryBuilder<Favorites> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Location_id.eq(null));
                location_TheLocationFavoriteQuery = queryBuilder.build();
            }
        }
        Query<Favorites> query = location_TheLocationFavoriteQuery.forCurrentThread();
        query.setParameter(0, location_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getLocationDao().getAllColumns());
            builder.append(" FROM FAVORITES T");
            builder.append(" LEFT JOIN USER T0 ON T.\"USER_ID\"=T0.\"_ID\"");
            builder.append(" LEFT JOIN LOCATION T1 ON T.\"LOCATION_ID\"=T1.\"_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Favorites loadCurrentDeep(Cursor cursor, boolean lock) {
        Favorites entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        User myFavorites = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
         if(myFavorites != null) {
            entity.setMyFavorites(myFavorites);
        }
        offset += daoSession.getUserDao().getAllColumns().length;

        Location myFavorite = loadCurrentOther(daoSession.getLocationDao(), cursor, offset);
        entity.setMyFavorite(myFavorite);

        return entity;    
    }

    public Favorites loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Favorites> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Favorites> list = new ArrayList<Favorites>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Favorites> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Favorites> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
