package com.optimussoftware.db;

import org.greenrobot.greendao.annotation.*;

import com.optimussoftware.db.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "IMAGE".
 */
@SuppressWarnings("ALL")
@Entity(active = true)
public class Image implements java.io.Serializable {

    @Id
    @NotNull
    @Unique
    private String _id;
    private String _etag;
    private java.util.Date created;
    private java.util.Date updated;
    private Boolean active;
    private Boolean deleted;
    private String name;
    private String file;
    private Integer width;
    private Integer height;
    private Integer position;

    @NotNull
    private String advertising_id;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient ImageDao myDao;

    @ToOne(joinProperty = "advertising_id")
    private Advertising images;

    @Generated
    private transient String images__resolvedKey;

    @Generated
    public Image() {
    }

    public Image(String _id) {
        this._id = _id;
    }

    @Generated
    public Image(String _id, String _etag, java.util.Date created, java.util.Date updated, Boolean active, Boolean deleted, String name, String file, Integer width, Integer height, Integer position, String advertising_id) {
        this._id = _id;
        this._etag = _etag;
        this.created = created;
        this.updated = updated;
        this.active = active;
        this.deleted = deleted;
        this.name = name;
        this.file = file;
        this.width = width;
        this.height = height;
        this.position = position;
        this.advertising_id = advertising_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getImageDao() : null;
    }

    @NotNull
    public String get_id() {
        return _id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void set_id(@NotNull String _id) {
        this._id = _id;
    }

    public String get_etag() {
        return _etag;
    }

    public void set_etag(String _etag) {
        this._etag = _etag;
    }

    public java.util.Date getCreated() {
        return created;
    }

    public void setCreated(java.util.Date created) {
        this.created = created;
    }

    public java.util.Date getUpdated() {
        return updated;
    }

    public void setUpdated(java.util.Date updated) {
        this.updated = updated;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFile() {
        return file;
    }

    public void setFile(String file) {
        this.file = file;
    }

    public Integer getWidth() {
        return width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    @NotNull
    public String getAdvertising_id() {
        return advertising_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAdvertising_id(@NotNull String advertising_id) {
        this.advertising_id = advertising_id;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public Advertising getImages() {
        String __key = this.advertising_id;
        if (images__resolvedKey == null || images__resolvedKey != __key) {
            __throwIfDetached();
            AdvertisingDao targetDao = daoSession.getAdvertisingDao();
            Advertising imagesNew = targetDao.load(__key);
            synchronized (this) {
                images = imagesNew;
            	images__resolvedKey = __key;
            }
        }
        return images;
    }

    @Generated
    public void setImages(@NotNull Advertising images) {
        if (images == null) {
            throw new DaoException("To-one property 'advertising_id' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.images = images;
            advertising_id = images.get_id();
            images__resolvedKey = advertising_id;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
