package com.optimussoftware.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INTEREST".
*/
public class InterestDao extends AbstractDao<Interest, String> {

    public static final String TABLENAME = "INTEREST";

    /**
     * Properties of entity Interest.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, String.class, "_id", true, "_ID");
        public final static Property _etag = new Property(1, String.class, "_etag", false, "_ETAG");
        public final static Property Created = new Property(2, java.util.Date.class, "created", false, "CREATED");
        public final static Property Updated = new Property(3, java.util.Date.class, "updated", false, "UPDATED");
        public final static Property Active = new Property(4, Boolean.class, "active", false, "ACTIVE");
        public final static Property Deleted = new Property(5, Boolean.class, "deleted", false, "DELETED");
        public final static Property Name = new Property(6, String.class, "name", false, "NAME");
        public final static Property Image = new Property(7, String.class, "image", false, "IMAGE");
        public final static Property Description = new Property(8, String.class, "description", false, "DESCRIPTION");
        public final static Property Indicator = new Property(9, Boolean.class, "indicator", false, "INDICATOR");
        public final static Property Campaign_id = new Property(10, String.class, "campaign_id", false, "CAMPAIGN_ID");
        public final static Property Advertising_id = new Property(11, String.class, "advertising_id", false, "ADVERTISING_ID");
    }

    private DaoSession daoSession;

    private Query<Interest> campaign_TheInterestCampaignQuery;
    private Query<Interest> advertising_TheInterestAdvertisingQuery;

    public InterestDao(DaoConfig config) {
        super(config);
    }
    
    public InterestDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INTEREST\" (" + //
                "\"_ID\" TEXT PRIMARY KEY NOT NULL UNIQUE ," + // 0: _id
                "\"_ETAG\" TEXT," + // 1: _etag
                "\"CREATED\" INTEGER," + // 2: created
                "\"UPDATED\" INTEGER," + // 3: updated
                "\"ACTIVE\" INTEGER," + // 4: active
                "\"DELETED\" INTEGER," + // 5: deleted
                "\"NAME\" TEXT," + // 6: name
                "\"IMAGE\" TEXT," + // 7: image
                "\"DESCRIPTION\" TEXT," + // 8: description
                "\"INDICATOR\" INTEGER," + // 9: indicator
                "\"CAMPAIGN_ID\" TEXT," + // 10: campaign_id
                "\"ADVERTISING_ID\" TEXT);"); // 11: advertising_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INTEREST\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Interest entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.get_id());
 
        String _etag = entity.get_etag();
        if (_etag != null) {
            stmt.bindString(2, _etag);
        }
 
        java.util.Date created = entity.getCreated();
        if (created != null) {
            stmt.bindLong(3, created.getTime());
        }
 
        java.util.Date updated = entity.getUpdated();
        if (updated != null) {
            stmt.bindLong(4, updated.getTime());
        }
 
        Boolean active = entity.getActive();
        if (active != null) {
            stmt.bindLong(5, active ? 1L: 0L);
        }
 
        Boolean deleted = entity.getDeleted();
        if (deleted != null) {
            stmt.bindLong(6, deleted ? 1L: 0L);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(7, name);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(8, image);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(9, description);
        }
 
        Boolean indicator = entity.getIndicator();
        if (indicator != null) {
            stmt.bindLong(10, indicator ? 1L: 0L);
        }
 
        String campaign_id = entity.getCampaign_id();
        if (campaign_id != null) {
            stmt.bindString(11, campaign_id);
        }
 
        String advertising_id = entity.getAdvertising_id();
        if (advertising_id != null) {
            stmt.bindString(12, advertising_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Interest entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.get_id());
 
        String _etag = entity.get_etag();
        if (_etag != null) {
            stmt.bindString(2, _etag);
        }
 
        java.util.Date created = entity.getCreated();
        if (created != null) {
            stmt.bindLong(3, created.getTime());
        }
 
        java.util.Date updated = entity.getUpdated();
        if (updated != null) {
            stmt.bindLong(4, updated.getTime());
        }
 
        Boolean active = entity.getActive();
        if (active != null) {
            stmt.bindLong(5, active ? 1L: 0L);
        }
 
        Boolean deleted = entity.getDeleted();
        if (deleted != null) {
            stmt.bindLong(6, deleted ? 1L: 0L);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(7, name);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(8, image);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(9, description);
        }
 
        Boolean indicator = entity.getIndicator();
        if (indicator != null) {
            stmt.bindLong(10, indicator ? 1L: 0L);
        }
 
        String campaign_id = entity.getCampaign_id();
        if (campaign_id != null) {
            stmt.bindString(11, campaign_id);
        }
 
        String advertising_id = entity.getAdvertising_id();
        if (advertising_id != null) {
            stmt.bindString(12, advertising_id);
        }
    }

    @Override
    protected final void attachEntity(Interest entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    @Override
    public Interest readEntity(Cursor cursor, int offset) {
        Interest entity = new Interest( //
            cursor.getString(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // _etag
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // created
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // updated
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // active
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // deleted
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // name
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // image
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // description
            cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0, // indicator
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // campaign_id
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11) // advertising_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Interest entity, int offset) {
        entity.set_id(cursor.getString(offset + 0));
        entity.set_etag(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCreated(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setUpdated(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setActive(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setDeleted(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setImage(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setDescription(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setIndicator(cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0);
        entity.setCampaign_id(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setAdvertising_id(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Interest entity, long rowId) {
        return entity.get_id();
    }
    
    @Override
    public String getKey(Interest entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Interest entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "theInterestCampaign" to-many relationship of Campaign. */
    public List<Interest> _queryCampaign_TheInterestCampaign(String campaign_id) {
        synchronized (this) {
            if (campaign_TheInterestCampaignQuery == null) {
                QueryBuilder<Interest> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Campaign_id.eq(null));
                campaign_TheInterestCampaignQuery = queryBuilder.build();
            }
        }
        Query<Interest> query = campaign_TheInterestCampaignQuery.forCurrentThread();
        query.setParameter(0, campaign_id);
        return query.list();
    }

    /** Internal query to resolve the "theInterestAdvertising" to-many relationship of Advertising. */
    public List<Interest> _queryAdvertising_TheInterestAdvertising(String advertising_id) {
        synchronized (this) {
            if (advertising_TheInterestAdvertisingQuery == null) {
                QueryBuilder<Interest> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Advertising_id.eq(null));
                advertising_TheInterestAdvertisingQuery = queryBuilder.build();
            }
        }
        Query<Interest> query = advertising_TheInterestAdvertisingQuery.forCurrentThread();
        query.setParameter(0, advertising_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCampaignDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getAdvertisingDao().getAllColumns());
            builder.append(" FROM INTEREST T");
            builder.append(" LEFT JOIN CAMPAIGN T0 ON T.\"CAMPAIGN_ID\"=T0.\"_ID\"");
            builder.append(" LEFT JOIN ADVERTISING T1 ON T.\"ADVERTISING_ID\"=T1.\"_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Interest loadCurrentDeep(Cursor cursor, boolean lock) {
        Interest entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Campaign theCampaigns = loadCurrentOther(daoSession.getCampaignDao(), cursor, offset);
        entity.setTheCampaigns(theCampaigns);
        offset += daoSession.getCampaignDao().getAllColumns().length;

        Advertising theInterests = loadCurrentOther(daoSession.getAdvertisingDao(), cursor, offset);
        entity.setTheInterests(theInterests);

        return entity;    
    }

    public Interest loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Interest> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Interest> list = new ArrayList<Interest>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Interest> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Interest> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
