package com.optimussoftware.db;

import org.greenrobot.greendao.annotation.*;

import com.optimussoftware.db.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "NOTIFICATION".
 */
@SuppressWarnings("ALL")
@Entity(active = true)
public class Notification implements java.io.Serializable {

    @Id
    @NotNull
    @Unique
    private String _id;
    private String _etag;
    private java.util.Date created;
    private java.util.Date updated;
    private Boolean active;
    private Boolean deleted;
    private Boolean read;
    private Boolean block;

    @NotNull
    private String advertising_id;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient NotificationDao myDao;

    @ToOne(joinProperty = "advertising_id")
    private Advertising theNotifi;

    @Generated
    private transient String theNotifi__resolvedKey;

    @Generated
    public Notification() {
    }

    public Notification(String _id) {
        this._id = _id;
    }

    @Generated
    public Notification(String _id, String _etag, java.util.Date created, java.util.Date updated, Boolean active, Boolean deleted, Boolean read, Boolean block, String advertising_id) {
        this._id = _id;
        this._etag = _etag;
        this.created = created;
        this.updated = updated;
        this.active = active;
        this.deleted = deleted;
        this.read = read;
        this.block = block;
        this.advertising_id = advertising_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getNotificationDao() : null;
    }

    @NotNull
    public String get_id() {
        return _id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void set_id(@NotNull String _id) {
        this._id = _id;
    }

    public String get_etag() {
        return _etag;
    }

    public void set_etag(String _etag) {
        this._etag = _etag;
    }

    public java.util.Date getCreated() {
        return created;
    }

    public void setCreated(java.util.Date created) {
        this.created = created;
    }

    public java.util.Date getUpdated() {
        return updated;
    }

    public void setUpdated(java.util.Date updated) {
        this.updated = updated;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    public Boolean getRead() {
        return read;
    }

    public void setRead(Boolean read) {
        this.read = read;
    }

    public Boolean getBlock() {
        return block;
    }

    public void setBlock(Boolean block) {
        this.block = block;
    }

    @NotNull
    public String getAdvertising_id() {
        return advertising_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAdvertising_id(@NotNull String advertising_id) {
        this.advertising_id = advertising_id;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public Advertising getTheNotifi() {
        String __key = this.advertising_id;
        if (theNotifi__resolvedKey == null || theNotifi__resolvedKey != __key) {
            __throwIfDetached();
            AdvertisingDao targetDao = daoSession.getAdvertisingDao();
            Advertising theNotifiNew = targetDao.load(__key);
            synchronized (this) {
                theNotifi = theNotifiNew;
            	theNotifi__resolvedKey = __key;
            }
        }
        return theNotifi;
    }

    @Generated
    public void setTheNotifi(@NotNull Advertising theNotifi) {
        if (theNotifi == null) {
            throw new DaoException("To-one property 'advertising_id' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.theNotifi = theNotifi;
            advertising_id = theNotifi.get_id();
            theNotifi__resolvedKey = advertising_id;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
