package com.optimussoftware.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "REVIEW".
*/
public class ReviewDao extends AbstractDao<Review, String> {

    public static final String TABLENAME = "REVIEW";

    /**
     * Properties of entity Review.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, String.class, "_id", true, "_ID");
        public final static Property _etag = new Property(1, String.class, "_etag", false, "_ETAG");
        public final static Property Created = new Property(2, java.util.Date.class, "created", false, "CREATED");
        public final static Property Updated = new Property(3, java.util.Date.class, "updated", false, "UPDATED");
        public final static Property Active = new Property(4, Boolean.class, "active", false, "ACTIVE");
        public final static Property Deleted = new Property(5, Boolean.class, "deleted", false, "DELETED");
        public final static Property Vote = new Property(6, Integer.class, "vote", false, "VOTE");
        public final static Property Comment = new Property(7, String.class, "comment", false, "COMMENT");
        public final static Property Lang = new Property(8, String.class, "lang", false, "LANG");
        public final static Property First_name = new Property(9, String.class, "first_name", false, "FIRST_NAME");
        public final static Property Last_name = new Property(10, String.class, "last_name", false, "LAST_NAME");
        public final static Property Profile_photo = new Property(11, String.class, "profile_photo", false, "PROFILE_PHOTO");
        public final static Property Advertising_id = new Property(12, String.class, "advertising_id", false, "ADVERTISING_ID");
        public final static Property User_id = new Property(13, String.class, "user_id", false, "USER_ID");
    }

    private DaoSession daoSession;

    private Query<Review> advertising_TheAdvertisingReviewQuery;
    private Query<Review> user_TheUserReviewsQuery;

    public ReviewDao(DaoConfig config) {
        super(config);
    }
    
    public ReviewDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"REVIEW\" (" + //
                "\"_ID\" TEXT PRIMARY KEY NOT NULL UNIQUE ," + // 0: _id
                "\"_ETAG\" TEXT," + // 1: _etag
                "\"CREATED\" INTEGER," + // 2: created
                "\"UPDATED\" INTEGER," + // 3: updated
                "\"ACTIVE\" INTEGER," + // 4: active
                "\"DELETED\" INTEGER," + // 5: deleted
                "\"VOTE\" INTEGER," + // 6: vote
                "\"COMMENT\" TEXT," + // 7: comment
                "\"LANG\" TEXT," + // 8: lang
                "\"FIRST_NAME\" TEXT," + // 9: first_name
                "\"LAST_NAME\" TEXT," + // 10: last_name
                "\"PROFILE_PHOTO\" TEXT," + // 11: profile_photo
                "\"ADVERTISING_ID\" TEXT NOT NULL ," + // 12: advertising_id
                "\"USER_ID\" TEXT NOT NULL );"); // 13: user_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"REVIEW\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Review entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.get_id());
 
        String _etag = entity.get_etag();
        if (_etag != null) {
            stmt.bindString(2, _etag);
        }
 
        java.util.Date created = entity.getCreated();
        if (created != null) {
            stmt.bindLong(3, created.getTime());
        }
 
        java.util.Date updated = entity.getUpdated();
        if (updated != null) {
            stmt.bindLong(4, updated.getTime());
        }
 
        Boolean active = entity.getActive();
        if (active != null) {
            stmt.bindLong(5, active ? 1L: 0L);
        }
 
        Boolean deleted = entity.getDeleted();
        if (deleted != null) {
            stmt.bindLong(6, deleted ? 1L: 0L);
        }
 
        Integer vote = entity.getVote();
        if (vote != null) {
            stmt.bindLong(7, vote);
        }
 
        String comment = entity.getComment();
        if (comment != null) {
            stmt.bindString(8, comment);
        }
 
        String lang = entity.getLang();
        if (lang != null) {
            stmt.bindString(9, lang);
        }
 
        String first_name = entity.getFirst_name();
        if (first_name != null) {
            stmt.bindString(10, first_name);
        }
 
        String last_name = entity.getLast_name();
        if (last_name != null) {
            stmt.bindString(11, last_name);
        }
 
        String profile_photo = entity.getProfile_photo();
        if (profile_photo != null) {
            stmt.bindString(12, profile_photo);
        }
        stmt.bindString(13, entity.getAdvertising_id());
        stmt.bindString(14, entity.getUser_id());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Review entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.get_id());
 
        String _etag = entity.get_etag();
        if (_etag != null) {
            stmt.bindString(2, _etag);
        }
 
        java.util.Date created = entity.getCreated();
        if (created != null) {
            stmt.bindLong(3, created.getTime());
        }
 
        java.util.Date updated = entity.getUpdated();
        if (updated != null) {
            stmt.bindLong(4, updated.getTime());
        }
 
        Boolean active = entity.getActive();
        if (active != null) {
            stmt.bindLong(5, active ? 1L: 0L);
        }
 
        Boolean deleted = entity.getDeleted();
        if (deleted != null) {
            stmt.bindLong(6, deleted ? 1L: 0L);
        }
 
        Integer vote = entity.getVote();
        if (vote != null) {
            stmt.bindLong(7, vote);
        }
 
        String comment = entity.getComment();
        if (comment != null) {
            stmt.bindString(8, comment);
        }
 
        String lang = entity.getLang();
        if (lang != null) {
            stmt.bindString(9, lang);
        }
 
        String first_name = entity.getFirst_name();
        if (first_name != null) {
            stmt.bindString(10, first_name);
        }
 
        String last_name = entity.getLast_name();
        if (last_name != null) {
            stmt.bindString(11, last_name);
        }
 
        String profile_photo = entity.getProfile_photo();
        if (profile_photo != null) {
            stmt.bindString(12, profile_photo);
        }
        stmt.bindString(13, entity.getAdvertising_id());
        stmt.bindString(14, entity.getUser_id());
    }

    @Override
    protected final void attachEntity(Review entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    @Override
    public Review readEntity(Cursor cursor, int offset) {
        Review entity = new Review( //
            cursor.getString(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // _etag
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // created
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // updated
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // active
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // deleted
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // vote
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // comment
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // lang
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // first_name
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // last_name
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // profile_photo
            cursor.getString(offset + 12), // advertising_id
            cursor.getString(offset + 13) // user_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Review entity, int offset) {
        entity.set_id(cursor.getString(offset + 0));
        entity.set_etag(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCreated(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setUpdated(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setActive(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setDeleted(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setVote(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setComment(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setLang(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setFirst_name(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setLast_name(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setProfile_photo(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setAdvertising_id(cursor.getString(offset + 12));
        entity.setUser_id(cursor.getString(offset + 13));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Review entity, long rowId) {
        return entity.get_id();
    }
    
    @Override
    public String getKey(Review entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Review entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "TheAdvertisingReview" to-many relationship of Advertising. */
    public List<Review> _queryAdvertising_TheAdvertisingReview(String advertising_id) {
        synchronized (this) {
            if (advertising_TheAdvertisingReviewQuery == null) {
                QueryBuilder<Review> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Advertising_id.eq(null));
                advertising_TheAdvertisingReviewQuery = queryBuilder.build();
            }
        }
        Query<Review> query = advertising_TheAdvertisingReviewQuery.forCurrentThread();
        query.setParameter(0, advertising_id);
        return query.list();
    }

    /** Internal query to resolve the "TheUserReviews" to-many relationship of User. */
    public List<Review> _queryUser_TheUserReviews(String user_id) {
        synchronized (this) {
            if (user_TheUserReviewsQuery == null) {
                QueryBuilder<Review> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.User_id.eq(null));
                user_TheUserReviewsQuery = queryBuilder.build();
            }
        }
        Query<Review> query = user_TheUserReviewsQuery.forCurrentThread();
        query.setParameter(0, user_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAdvertisingDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getUserDao().getAllColumns());
            builder.append(" FROM REVIEW T");
            builder.append(" LEFT JOIN ADVERTISING T0 ON T.\"ADVERTISING_ID\"=T0.\"_ID\"");
            builder.append(" LEFT JOIN USER T1 ON T.\"USER_ID\"=T1.\"_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Review loadCurrentDeep(Cursor cursor, boolean lock) {
        Review entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Advertising theReview = loadCurrentOther(daoSession.getAdvertisingDao(), cursor, offset);
         if(theReview != null) {
            entity.setTheReview(theReview);
        }
        offset += daoSession.getAdvertisingDao().getAllColumns().length;

        User theReviews = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
         if(theReviews != null) {
            entity.setTheReviews(theReviews);
        }

        return entity;    
    }

    public Review loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Review> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Review> list = new ArrayList<Review>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Review> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Review> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
